ekf_filter_node:
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        publish_tf: true

        print_diagnostics: true
        debug: true
        debug_out_file: /home/jetson/Develop/Robot/nav_mecanum_ws/log/ekf_log.txt

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom
        transform_time_offset: 0.1
        transform_timeout: 0.1
        sensor_timeout: 0.2
        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az
        odom0: odom/wheel
        odom0_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]
        odom1: odom/laser
        odom1_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]
        imu0: imu/data
        imu0_config: [false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, true,
                      true, true, false]