controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # joint_state_broadcaster:
    #   type: joint_state_broadcaster/JointStateBroadcaster

    # forward_position_controller:              # delete entry if controller is not applicable
    #   type: forward_command_controller/ForwardCommandController

    # forward_velocity_controller:              # delete entry if controller is not applicable
    #   type: forward_command_controller/ForwardCommandController

    # joint_trajectory_controller:              # delete entry if controller is not applicable
    #   type: joint_trajectory_controller/JointTrajectoryController

    nav_mecanum_controller:
      type: nav_mecanum_controller/NavMecanumController

# forward_position_controller:                  # delete entry if controller is not applicable
#   ros__parameters:
#     joints:
#       - joint1
#       - joint2
#       - joint3
#       - joint4
#     interface_name: position

# forward_velocity_controller:                  # delete entry if controller is not applicable
#   ros__parameters:
#     joints:
#       - joint1
#       - joint2
#       - joint3
#       - joint4
#     interface_name: velocity

# joint_trajectory_controller:                  # delete entry if controller is not applicable
#   ros__parameters:
#     joints:
#       - joint1
#       - joint2
#       - joint3
#       - joint4

#     state_publish_rate: 50.0 # Defaults to 50
#     action_monitor_rate: 20.0 # Defaults to 20

#     allow_partial_joints_goal: false # Defaults to false
#     constraints:
#       stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)

nav_mecanum_controller:
  ros__parameters:
    left_front_wheel_name: ["left_front_wheel_joint"]
    left_rear_wheel_name: ["left_rear_wheel_joint"]
    right_front_wheel_name: ["right_front_wheel_joint"]
    right_rear_wheel_name: ["right_rear_wheel_joint"]

    wheel_separation_front_and_rear: 0.10
    wheel_separation_left_and_right: 0.15
    wheel_radius: 0.075
    odom_subscribe_topic: "odom/filtered"
    imu_subscribe_topic: "imu/data"
    twist_publish_topic: "cmd_vel_mecanum"
    
    publish_rate: 50.0 # Hz

    linear.max_velocity: 1.0
    linear.min_velocity: -1.0
    linear.min_acceleration: -1.0
    linear.max_acceleration: 1.0

    angular.max_velocity: 1.0
    angular.min_velocity: -1.0
    angular.max_acceleration: 1.0
    angular.min_acceleration: -1.0
